package main

const DEFAULT_HEALTH_CHECKER_RESPONSE_HEADER_TIMEOUT = 10
const DEFAULT_HEALTH_CHECKER_TIMEOUT_STEP = 2
const DEFAULT_HEALTH_CHECKER_PERIOD = 10
const DEFAULT_HEALTH_CHECKER_MAX_RETRIES = 3

const DEFAULT_BALANCER_RESPONSE_HEADER_TIMEOUT = 10

const DEFAULT_ALGO = "roundrobin"
